# Generated by Django 3.0.6 on 2020-06-05 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200602_0334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zip_code',
            new_name='zipcode',
        ),
    ]
